In [1]:
print("hello")

hello

In [2]:
import numpy as np
import pandas as pd

In [3]:
movies=pd.read_csv('tmdb_5000_movies.csv')
credits=pd.read_csv('tmdb_5000_credits.csv')

In [4]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [5]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [6]:
movies=movies.merge(credits, on='title')

In [7]:
# imp tags for making recomendation
# id
#genre
#keywords
#title
#overview
#cast
#crew
movies=movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [8]:
movies.shape

(4809, 7)

In [9]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   str
 2   overview  4806 non-null   str
 3   genres    4809 non-null   str
 4   keywords  4809 non-null   str
 5   cast      4809 non-null   str
 6   crew      4809 non-null   str
dtypes: int64(1), str(6)
memory usage: 37.0 MB

In [10]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [11]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [12]:
movies.dropna(inplace=True)

In [13]:
movies.duplicated().sum()

np.int64(0)

In [14]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
import ast

def convert(obj):
    L=[]
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [16]:
movies['genres']=movies['genres'].apply(convert)

In [17]:
movies['keywords']=movies['keywords'].apply(convert)

In [18]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
def convert3(obj):
    L=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter !=3:
            L.append(i['name'])
            counter+=1
        else:
            break
    return L

In [20]:
movies['cast']=movies['cast'].apply(convert3)

In [21]:
def fetch_director(obj):
    L=[]
    for i in ast.literal_eval(obj):
        if i['job']=='director':
            L.append(i['name'])
        break
    return L

In [22]:
movies['crew']=movies['crew'].apply(fetch_director)

In [23]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [24]:
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

In [25]:
movies['tags']= movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [26]:
new_df=movies[['movie_id','title','tags']]

In [27]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [28]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [29]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [30]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

new_df['tags']=new_df['tags'].apply(stem)

In [31]:
# now i converting text int vector so machine can catch all near vector
#for that i am bus "bag of words" technique

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [33]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [34]:
from sklearn.metrics.pairwise import cosine_similarity

In [35]:
similarity=cosine_similarity(vectors)

In [36]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, np.float64(1.0000000000000002)),
 (1214, np.float64(0.2847987184339659)),
 (2405, np.float64(0.26600795837367097)),
 (3728, np.float64(0.2605130246476754)),
 (507, np.float64(0.257841025556124)),
 (539, np.float64(0.2503866978335957)),
 (582, np.float64(0.24511108480187255)),
 (1202, np.float64(0.24455799402225925)),
 (1192, np.float64(0.2367785320221084)),
 (61, np.float64(0.23179316248638274)),
 (778, np.float64(0.23174488732966075)),
 (4046, np.float64(0.2278389747471728)),
 (1916, np.float64(0.22528177844479153)),
 (2782, np.float64(0.21853668936906193)),
 (972, np.float64(0.2108663315950723)),
 (322, np.float64(0.2105263157894737)),
 (172, np.float64(0.2075143391598224)),
 (151, np.float64(0.20751433915982237)),
 (973, np.float64(0.2073221072156823)),
 (2329, np.float64(0.20647416048350561)),
 (74, np.float64(0.2044398826909146)),
 (3606, np.float64(0.20437977982832192)),
 (260, np.float64(0.20395079136182276)),
 (4190, np.float64(0.2029530274475215)),
 (1440, np.float64(0.20277677641345318)),
 (1087, np.float64(0.2020475485519274)),
 (577, np.float64(0.20073876713674155)),
 (3671, np.float64(0.1979082783981174)),
 (47, np.float64(0.19529164171612676)),
 (2969, np.float64(0.19389168358237033)),
 (942, np.float64(0.19134594929397597)),
 (495, np.float64(0.19088542889273336)),
 (1199, np.float64(0.19088542889273336)),
 (305, np.float64(0.1900748713929803)),
 (4, np.float64(0.18929940971212042)),
 (27, np.float64(0.18848425873126295)),
 (4405, np.float64(0.18731716231633883)),
 (94, np.float64(0.1873171623163388)),
 (2997, np.float64(0.1860807318911967)),
 (3325, np.float64(0.1860807318911967)),
 (1273, np.float64(0.18394180184548975)),
 (1327, np.float64(0.18394180184548975)),
 (1319, np.float64(0.1813690625275029)),
 (220, np.float64(0.18074256993863339)),
 (83, np.float64(0.17996850826633903)),
 (1069, np.float64(0.17954621161490197)),
 (3997, np.float64(0.1777046633277277)),
 (4336, np.float64(0.177343107178349)),
 (373, np.float64(0.17699808135119718)),
 (168, np.float64(0.17521916101261562)),
 (184, np.float64(0.17521916101261562)),
 (2200, np.float64(0.17521916101261562)),
 (931, np.float64(0.1748149640244195)),
 (36, np.float64(0.17316974359835272)),
 (838, np.float64(0.17206180040292135)),
 (3536, np.float64(0.1711905958155815)),
 (3160, np.float64(0.17040572913692198)),
 (91, np.float64(0.16943474841747155)),
 (300, np.float64(0.1692777916923361)),
 (1827, np.float64(0.1692777916923361)),
 (661, np.float64(0.1675415633166782)),
 (41, np.float64(0.16742770563222897)),
 (529, np.float64(0.16742770563222897)),
 (1978, np.float64(0.16692446522239715)),
 (150, np.float64(0.16531163063339513)),
 (342, np.float64(0.16222142113076254)),
 (595, np.float64(0.16059101370939324)),
 (1533, np.float64(0.16059101370939322)),
 (67, np.float64(0.1600142241187995)),
 (31, np.float64(0.15907119074394446)),
 (2511, np.float64(0.15907119074394446)),
 (1176, np.float64(0.15789473684210528)),
 (4008, np.float64(0.15737789507292674)),
 (149, np.float64(0.1562333133729014)),
 (581, np.float64(0.15609763526361567)),
 (2727, np.float64(0.15609763526361567)),
 (26, np.float64(0.15389675281277312)),
 (187, np.float64(0.15389675281277312)),
 (1379, np.float64(0.15389675281277312)),
 (111, np.float64(0.152008377581442)),
 (513, np.float64(0.15018785229652767)),
 (1342, np.float64(0.15018785229652767)),
 (52, np.float64(0.14843120879858804)),
 (311, np.float64(0.14843120879858804)),
 (2071, np.float64(0.14808721943977307)),
 (127, np.float64(0.146943671674129)),
 (7, np.float64(0.14673479641335554)),
 (275, np.float64(0.14567913668701626)),
 (579, np.float64(0.14567913668701626)),
 (2756, np.float64(0.1453922723390424)),
 (108, np.float64(0.14509525002200235)),
 (1295, np.float64(0.14509525002200235)),
 (1353, np.float64(0.14509525002200235)),
 (466, np.float64(0.14509525002200233)),
 (1475, np.float64(0.14421498760030763)),
 (1934, np.float64(0.14350946197048198)),
 (294, np.float64(0.1433848336691011)),
 (413, np.float64(0.1433848336691011)),
 (568, np.float64(0.1433848336691011)),
 (1392, np.float64(0.14306584587982535)),
 (95, np.float64(0.1419745572840903)),
 (1271, np.float64(0.1419745572840903)),
 (1961, np.float64(0.14194374348941724)),
 (490, np.float64(0.14159846508095775)),
 (1484, np.float64(0.14159846508095775)),
 (46, np.float64(0.1411956236812263)),
 (2492, np.float64(0.1411956236812263)),
 (3352, np.float64(0.1411956236812263)),
 (1054, np.float64(0.14048787173725413)),
 (461, np.float64(0.1391037210186643)),
 (859, np.float64(0.1391037210186643)),
 (2165, np.float64(0.1391037210186643)),
 (3407, np.float64(0.1391037210186643)),
 (17, np.float64(0.13872950617564817)),
 (56, np.float64(0.13834289277321493)),
 (249, np.float64(0.13834289277321493)),
 (1325, np.float64(0.13834289277321493)),
 (3779, np.float64(0.13834289277321493)),
 (72, np.float64(0.13710212427677043)),
 (4077, np.float64(0.13710212427677043)),
 (4538, np.float64(0.13629325512727639)),
 (505, np.float64(0.13530201829834768)),
 (668, np.float64(0.13530201829834768)),
 (935, np.float64(0.13530201829834768)),
 (3980, np.float64(0.13530201829834768)),
 (843, np.float64(0.13518451760896877)),
 (1804, np.float64(0.13518451760896877)),
 (1320, np.float64(0.13476498501489081)),
 (158, np.float64(0.13369695534647594)),
 (502, np.float64(0.13369695534647594)),
 (777, np.float64(0.13369695534647594)),
 (126, np.float64(0.13334518676566626)),
 (1013, np.float64(0.13334518676566626)),
 (1556, np.float64(0.13334518676566626)),
 (476, np.float64(0.1324532357065044)),
 (1369, np.float64(0.1324532357065044)),
 (2374, np.float64(0.1324532357065044)),
 (2580, np.float64(0.1324532357065044)),
 (2129, np.float64(0.13124359177794215)),
 (4348, np.float64(0.130066495428618)),
 (14, np.float64(0.12988108336653278)),
 (3620, np.float64(0.12988108336653278)),
 (134, np.float64(0.12977713690461004)),
 (368, np.float64(0.12977713690461004)),
 (1770, np.float64(0.12977713690461004)),
 (2869, np.float64(0.12892051277806202)),
 (138, np.float64(0.12824729401064427)),
 (2177, np.float64(0.12824729401064427)),
 (2682, np.float64(0.12824729401064427)),
 (4228, np.float64(0.12824729401064427)),
 (483, np.float64(0.12725695259515557)),
 (487, np.float64(0.12725695259515557)),
 (773, np.float64(0.12725695259515557)),
 (1156, np.float64(0.12725695259515557)),
 (2968, np.float64(0.12725695259515557)),
 (1737, np.float64(0.1267165809286535)),
 (369, np.float64(0.126673647984535)),
 (937, np.float64(0.126673647984535)),
 (1084, np.float64(0.126673647984535)),
 (2476, np.float64(0.12565617248750865)),
 (166, np.float64(0.12515654358043973)),
 (754, np.float64(0.12515654358043973)),
 (2446, np.float64(0.12515654358043973)),
 (3626, np.float64(0.12515654358043973)),
 (208, np.float64(0.12487810821089254)),
 (1094, np.float64(0.12487810821089254)),
 (2056, np.float64(0.12487810821089254)),
 (102, np.float64(0.12462194771917919)),
 (557, np.float64(0.12369267399882337)),
 (1874, np.float64(0.12361284651454939)),
 (84, np.float64(0.12361284651454937)),
 (68, np.float64(0.12262786789699316)),
 (2648, np.float64(0.12262786789699316)),
 (438, np.float64(0.12227899701112963)),
 (1297, np.float64(0.12227899701112963)),
 (2327, np.float64(0.12166606584807191)),
 (2670, np.float64(0.12166606584807191)),
 (2785, np.float64(0.12166606584807191)),
 (3081, np.float64(0.12166606584807191)),
 (549, np.float64(0.12091270835166862)),
 (2280, np.float64(0.12091270835166862)),
 (139, np.float64(0.12072654548783007)),
 (781, np.float64(0.1204950466257556)),
 (1002, np.float64(0.1204950466257556)),
 (1272, np.float64(0.1204950466257556)),
 (1654, np.float64(0.1204950466257556)),
 (3374, np.float64(0.1204950466257556)),
 (3734, np.float64(0.1204950466257556)),
 (4673, np.float64(0.1204950466257556)),
 (1000, np.float64(0.11980845957463077)),
 (870, np.float64(0.11959121830873498)),
 (900, np.float64(0.11959121830873498)),
 (3233, np.float64(0.11959121830873498)),
 (1045, np.float64(0.11846977555181847)),
 (1299, np.float64(0.11846977555181847)),
 (1829, np.float64(0.11846977555181847)),
 (2737, np.float64(0.11846977555181847)),
 (278, np.float64(0.11831213107007527)),
 (1711, np.float64(0.11803342130469506)),
 (3719, np.float64(0.11803342130469506)),
 (1669, np.float64(0.11803342130469505)),
 (3998, np.float64(0.11803342130469505)),
 (160, np.float64(0.11712303424679457)),
 (182, np.float64(0.11707322644771176)),
 (1613, np.float64(0.11707322644771176)),
 (28, np.float64(0.116543309349613)),
 (122, np.float64(0.116543309349613)),
 (236, np.float64(0.116543309349613)),
 (422, np.float64(0.116543309349613)),
 (678, np.float64(0.116543309349613)),
 (589, np.float64(0.1163350101494222)),
 (454, np.float64(0.11587244366483038)),
 (2543, np.float64(0.11587244366483038)),
 (1493, np.float64(0.11551284429847784)),
 (3210, np.float64(0.11506355109724453)),
 (189, np.float64(0.1147078669352809)),
 (1571, np.float64(0.1147078669352809)),
 (1218, np.float64(0.11470786693528089)),
 (50, np.float64(0.11470786693528087)),
 (4777, np.float64(0.11470786693528087)),
 (85, np.float64(0.11412706387705432)),
 (432, np.float64(0.11357771260606365)),
 (1414, np.float64(0.11357771260606365)),
 (121, np.float64(0.11295649894498103)),
 (232, np.float64(0.11295649894498103)),
 (1612, np.float64(0.11295649894498103)),
 (420, np.float64(0.1124803176664619)),
 (536, np.float64(0.1124803176664619)),
 (889, np.float64(0.11243619908556624)),
 (3145, np.float64(0.11239029738980327)),
 (256, np.float64(0.11164843913471803)),
 (808, np.float64(0.11164843913471803)),
 (1346, np.float64(0.11164843913471803)),
 (2319, np.float64(0.11164843913471803)),
 (123, np.float64(0.11141412945539662)),
 (2368, np.float64(0.11141412945539662)),
 (1508, np.float64(0.11141412945539661)),
 (87, np.float64(0.11128297681493143)),
 (3006, np.float64(0.11128297681493143)),
 (4468, np.float64(0.11128297681493143)),
 (206, np.float64(0.11092107999698035)),
 (238, np.float64(0.11092107999698035)),
 (228, np.float64(0.11037769642208699)),
 (3307, np.float64(0.11037769642208699)),
 (1570, np.float64(0.11020775375559674)),
 (3426, np.float64(0.10968169942141637)),
 (21, np.float64(0.10968169942141635)),
 (449, np.float64(0.10968169942141635)),
 (1029, np.float64(0.10968169942141635)),
 (2068, np.float64(0.10968169942141635)),
 (81, np.float64(0.1095080149111477)),
 (5, np.float64(0.10936965981495178)),
 (692, np.float64(0.10936965981495178)),
 (200, np.float64(0.10882143751650175)),
 (627, np.float64(0.10882143751650175)),
 (653, np.float64(0.10882143751650175)),
 (1497, np.float64(0.10882143751650175)),
 (1520, np.float64(0.10882143751650175)),
 (307, np.float64(0.10876595882948199)),
 (3091, np.float64(0.10838874619051501)),
 (3628, np.float64(0.10838874619051501)),
 (572, np.float64(0.108388746190515)),
 (740, np.float64(0.108388746190515)),
 (332, np.float64(0.10814761408717502)),
 (472, np.float64(0.10814761408717502)),
 (786, np.float64(0.10814761408717502)),
 (1941, np.float64(0.10814761408717502)),
 (3496, np.float64(0.10814761408717502)),
 (229, np.float64(0.1074861545850028)),
 (262, np.float64(0.10743376064838502)),
 (939, np.float64(0.1068366854693644)),
 (1235, np.float64(0.106676149412533)),
 (541, np.float64(0.10650358071057624)),
 (1164, np.float64(0.10619884881071831)),
 (1741, np.float64(0.10619884881071831)),
 (2157, np.float64(0.10619884881071831)),
 (2517, np.float64(0.10619884881071831)),
 (2630, np.float64(0.10619884881071831)),
 (4133, np.float64(0.10619884881071831)),
 (170, np.float64(0.10559715077387793)),
 (467, np.float64(0.10559715077387793)),
 (131, np.float64(0.10526315789473685)),
 (295, np.float64(0.10526315789473685)),
 (687, np.float64(0.10526315789473685)),
 (814, np.float64(0.10526315789473685)),
 (1035, np.float64(0.10526315789473685)),
 (1767, np.float64(0.10526315789473685)),
 (3338, np.float64(0.10526315789473685)),
 (1492, np.float64(0.10471347707292386)),
 (10, np.float64(0.10390486669322622)),
 (75, np.float64(0.10390486669322622)),
 (223, np.float64(0.10390486669322622)),
 (643, np.float64(0.10390486669322622)),
 (1193, np.float64(0.10390486669322622)),
 (2144, np.float64(0.10390486669322622)),
 (2813, np.float64(0.10390486669322622)),
 (3753, np.float64(0.10390486669322622)),
 (2435, np.float64(0.103851623099316)),
 (2494, np.float64(0.103851623099316)),
 (654, np.float64(0.10385162309931599)),
 (2102, np.float64(0.10385162309931599)),
 (105, np.float64(0.1037571695799112)),
 (157, np.float64(0.1037571695799112)),
 (233, np.float64(0.1037571695799112)),
 (2452, np.float64(0.1037571695799112)),
 (2758, np.float64(0.1037571695799112)),
 (3053, np.float64(0.1037571695799112)),
 (3619, np.float64(0.1037571695799112)),
 (3837, np.float64(0.1037571695799112)),
 (1451, np.float64(0.10301070542879115)),
 (508, np.float64(0.10259783520851541)),
 (1080, np.float64(0.10259783520851541)),
 (3150, np.float64(0.10259783520851541)),
 (3632, np.float64(0.10259783520851541)),
 (3872, np.float64(0.10259783520851541)),
 (4095, np.float64(0.10259783520851541)),
 (35, np.float64(0.10147651372376076)),
 (319, np.float64(0.10147651372376076)),
 (624, np.float64(0.10147651372376076)),
 (1075, np.float64(0.10147651372376076)),
 (2049, np.float64(0.10147651372376076)),
 (3659, np.float64(0.10147651372376076)),
 (3952, np.float64(0.10147651372376076)),
 (3439, np.float64(0.10138838820672659)),
 (312, np.float64(0.101338918387628)),
 (330, np.float64(0.101338918387628)),
 (1292, np.float64(0.101338918387628)),
 (491, np.float64(0.10060545457319173)),
 (1401, np.float64(0.10060545457319173)),
 (1435, np.float64(0.10060545457319173)),
 (207, np.float64(0.10012523486435178)),
 (445, np.float64(0.10012523486435178)),
 (986, np.float64(0.10012523486435178)),
 (1397, np.float64(0.10012523486435178)),
 (1610, np.float64(0.10012523486435178)),
 (2243, np.float64(0.10012523486435176)),
 (2095, np.float64(0.09984038297885897)),
 (33, np.float64(0.09933992677987831)),
 (263, np.float64(0.09933992677987831)),
 (325, np.float64(0.09933992677987831)),
 (715, np.float64(0.09933992677987831)),
 (1278, np.float64(0.09933992677987831)),
 (1880, np.float64(0.09933992677987831)),
 (2783, np.float64(0.09933992677987831)),
 (4016, np.float64(0.09933992677987831)),
 (4196, np.float64(0.09933992677987831)),
 (4331, np.float64(0.09933992677987831)),
 (4490, np.float64(0.09933992677987831)),
 (363, np.float64(0.09909250441117726)),
 (1771, np.float64(0.09909250441117726)),
 (266, np.float64(0.0989541391990587)),
 (510, np.float64(0.0989541391990587)),
 (3618, np.float64(0.0989541391990587)),
 (3781, np.float64(0.0989541391990587)),
 (3933, np.float64(0.0989541391990587)),
 (9, np.float64(0.0978231976089037)),
 (480, np.float64(0.0978231976089037)),
 (535, np.float64(0.0978231976089037)),
 (898, np.float64(0.0978231976089037)),
 (1819, np.float64(0.0978231976089037)),
 (2249, np.float64(0.0978231976089037)),
 (362, np.float64(0.09733285267845754)),
 (878, np.float64(0.09733285267845754)),
 (1154, np.float64(0.09733285267845754)),
 (1723, np.float64(0.09733285267845754)),
 (1938, np.float64(0.09733285267845754)),
 (2558, np.float64(0.09733285267845754)),
 (4403, np.float64(0.09733285267845754)),
 (4472, np.float64(0.09733285267845754)),
 (371, np.float64(0.0967301666813349)),
 (410, np.float64(0.0967301666813349)),
 (1107, np.float64(0.0967301666813349)),
 (2237, np.float64(0.0967301666813349)),
 (11, np.float64(0.09567297464698798)),
 (334, np.float64(0.09567297464698798)),
 (412, np.float64(0.09567297464698798)),
 (2552, np.float64(0.09567297464698798)),
 (18, np.float64(0.09558988911273408)),
 (4545, np.float64(0.09558988911273408)),
 (148, np.float64(0.09544271444636668)),
 (791, np.float64(0.09544271444636668)),
 (1025, np.float64(0.09544271444636668)),
 (4201, np.float64(0.09544271444636668)),
 (4254, np.float64(0.09544271444636668)),
 (1992, np.float64(0.09464970485606021)),
 (129, np.float64(0.09365858115816941)),
 (243, np.float64(0.09365858115816941)),
 (511, np.float64(0.09365858115816941)),
 (660, np.float64(0.09365858115816941)),
 (813, np.float64(0.09365858115816941)),
 (920, np.float64(0.09365858115816941)),
 (1274, np.float64(0.09365858115816941)),
 (1355, np.float64(0.09365858115816941)),
 (1470, np.float64(0.09365858115816941)),
 (1569, np.float64(0.09365858115816941)),
 (1682, np.float64(0.09365858115816941)),
 (1688, np.float64(0.09365858115816941)),
 (1717, np.float64(0.09365858115816941)),
 (2089, np.float64(0.09365858115816941)),
 (2392, np.float64(0.09365858115816941)),
 (2484, np.float64(0.09365858115816941)),
 (2588, np.float64(0.09365858115816941)),
 (2641, np.float64(0.09365858115816941)),
 (2816, np.float64(0.09365858115816941)),
 (3535, np.float64(0.09365858115816941)),
 (3718, np.float64(0.09365858115816941)),
 (4502, np.float64(0.09365858115816941)),
 (301, np.float64(0.09365858115816939)),
 (785, np.float64(0.09304036594559835)),
 (799, np.float64(0.09304036594559835)),
 (473, np.float64(0.09269795493186431)),
 (596, np.float64(0.09269795493186431)),
 (1442, np.float64(0.09269795493186431)),
 (2646, np.float64(0.09269795493186431)),
 (3405, np.float64(0.09269795493186431)),
 (219, np.float64(0.09197090092274487)),
 (244, np.float64(0.09197090092274487)),
 (356, np.float64(0.09197090092274487)),
 (978, np.float64(0.09197090092274487)),
 (1304, np.float64(0.09197090092274487)),
 (1752, np.float64(0.09197090092274487)),
 (2647, np.float64(0.09197090092274487)),
 (230, np.float64(0.09183979479633063)),
 (1697, np.float64(0.09176629354822471)),
 (239, np.float64(0.09125667909262308)),
 (2566, np.float64(0.09125667909262308)),
 (43, np.float64(0.09086217008485092)),
 (602, np.float64(0.09086217008485092)),
 (995, np.float64(0.09086217008485092)),
 (1231, np.float64(0.09086217008485092)),
 (1842, np.float64(0.09086217008485092)),
 (3879, np.float64(0.09086217008485092)),
 (12, np.float64(0.09037128496931669)),
 (88, np.float64(0.09037128496931669)),
 (167, np.float64(0.09037128496931669)),
 (389, np.float64(0.09037128496931669)),
 (400, np.float64(0.09037128496931669)),
 (564, np.float64(0.09037128496931669)),
 (1476, np.float64(0.09037128496931669)),
 (2247, np.float64(0.09037128496931669)),
 (2955, np.float64(0.09037128496931669)),
 (274, np.float64(0.09005496868564147)),
 (331, np.float64(0.08998425413316952)),
 (2359, np.float64(0.08998425413316952)),
 (2792, np.float64(0.08998425413316952)),
 (2852, np.float64(0.08998425413316952)),
 (3387, np.float64(0.08998425413316952)),
 (3460, np.float64(0.08998425413316952)),
 (4343, np.float64(0.08998425413316952)),
 (4353, np.float64(0.08998425413316952)),
 (270, np.float64(0.0891313035643173)),
 (1902, np.float64(0.0891313035643173)),
 (2111, np.float64(0.08903057122447033)),
 (23, np.float64(0.08885233166386385)),
 (292, np.float64(0.08885233166386385)),
 (457, np.float64(0.08885233166386385)),
 (960, np.float64(0.08885233166386385)),
 (1257, np.float64(0.08885233166386385)),
 (1585, np.float64(0.08885233166386385)),
 (2656, np.float64(0.08885233166386385)),
 (2864, np.float64(0.08885233166386385)),
 (3320, np.float64(0.08885233166386385)),
 (3447, np.float64(0.08885233166386385)),
 (618, np.float64(0.08830215713766959)),
 (752, np.float64(0.08830215713766959)),
 (1779, np.float64(0.08830215713766959)),
 (2105, np.float64(0.08830215713766959)),
 (2736, np.float64(0.08830215713766959)),
 (3551, np.float64(0.08830215713766959)),
 (479, np.float64(0.08797691788472335)),
 (169, np.float64(0.08749572785196143)),
 (2709, np.float64(0.08749572785196143)),
 (2444, np.float64(0.08746392856766495)),
 (2, np.float64(0.08740748201220976)),
 (141, np.float64(0.08740748201220976)),
 (745, np.float64(0.08740748201220976)),
 (1247, np.float64(0.08740748201220976)),
 (3446, np.float64(0.08740748201220976)),
 (143, np.float64(0.08671099695241201)),
 (534, np.float64(0.08671099695241201)),
 (827, np.float64(0.08671099695241201)),
 (1017, np.float64(0.08671099695241201)),
 (1526, np.float64(0.08671099695241201)),
 (1828, np.float64(0.08671099695241201)),
 (2350, np.float64(0.08671099695241201)),

In [37]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    
    movies_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [38]:
recommend('Avatar')

Aliens vs Predator: Requiem
Aliens
Falcon Rising
Independence Day
Titan A.E.

In [39]:
import pickle

In [40]:
pickle.dump(new_df,open('movie.pkl','wb'))

In [41]:
new_df['title'].values

<ArrowStringArray>
[                                  'Avatar',
 'Pirates of the Caribbean: At World's End',
                                  'Spectre',
                    'The Dark Knight Rises',
                              'John Carter',
                             'Spider-Man 3',
                                  'Tangled',
                  'Avengers: Age of Ultron',
   'Harry Potter and the Half-Blood Prince',
       'Batman v Superman: Dawn of Justice',
 ...
                           'On The Downlow',
             'Sanctuary: Quite a Conundrum',
                                     'Bang',
                                   'Primer',
                                   'Cavite',
                              'El Mariachi',
                                'Newlyweds',
                'Signed, Sealed, Delivered',
                         'Shanghai Calling',
                        'My Date with Drew']
Length: 4806, dtype: str

In [42]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

In [44]:
pickle.dump(similarity,open('similarity.pkl','wb'))